### ISSUE TITLE
Can not install filibuster via pip

### ISSUE THREAD

**Issue by chMatvey** [filibuster-testing/filibuster-documentation#1]
Hi, I try to install Filibuster via pipe like in tutorial.
However I get this error:

ERROR: Could not find a version that satisfies the requirement filibuster (from versions: none)
ERROR: No matching distribution found for filibuster

**Comment by cmeiklejohn** [comment]
It looks like our pip packages aren't published.

Can you try installing it by source using the following:

```
git clone http://github.com/filibuster-testing/filibuster
cd filibuster
make install
```

Apologies for the confusion.

**Comment by chMatvey** [comment]
Thanks for answer. It works.
I've been doing other projects, hence the lack of communication.

**Comment by cmeiklejohn** [comment]
Opened PR #3 to fix documentation.
